---
- name: update repo
  apt:
    update_cache: yes

- name: install python3-pip python3-dev build-essential libssl-dev libffi-dev python3-setuptools
  apt:
    name:
      - python3-pip=22.0.2+dfsg-1ubuntu0.3
      - python3-dev=3.10.6-1~22.04
      - build-essential=12.9ubuntu3
      - libssl-dev=3.0.2-0ubuntu1.10
      - libffi-dev=3.4.2-4
      - python3-setuptools=59.6.0-1.2ubuntu0.22.04.1

- name: install gunicorn flask
  pip:
    name:
      - flask==2.3.2
      - gunicorn==21.2.0
      - requests==2.31.0

- name: source .profile
  become: true
  shell: source /home/ubuntu/.profile
  args:
    executable: /bin/bash